name: Release
on: [workflow_dispatch]
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2.1.4

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Run semantic-release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [tag]
    steps:
      - name: Install devmapper
        run: sudo apt-get install -y libdevmapper-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15.0
        id: go

      - name: Login to github registry
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}    

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
